platform :ios, '10.1'
use_frameworks!

target 'DogRunGeoCoder' do

 	pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

end 

  
